/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as TravelInsuranceRouteImport } from './routes/travel-insurance'
import { Route as InternationalToursRouteImport } from './routes/international-tours'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EgyptRouteImport } from './routes/egypt'
import { Route as DomesticToursRouteImport } from './routes/domestic-tours'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as CustomItineraryRouteImport } from './routes/custom-itinerary'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogsRouteImport } from './routes/blogs'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToursTourIdRouteImport } from './routes/tours.$tourId'
import { Route as BlogsSlugRouteImport } from './routes/blogs.$slug'

const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelInsuranceRoute = TravelInsuranceRouteImport.update({
  id: '/travel-insurance',
  path: '/travel-insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalToursRoute = InternationalToursRouteImport.update({
  id: '/international-tours',
  path: '/international-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EgyptRoute = EgyptRouteImport.update({
  id: '/egypt',
  path: '/egypt',
  getParentRoute: () => rootRouteImport,
} as any)
const DomesticToursRoute = DomesticToursRouteImport.update({
  id: '/domestic-tours',
  path: '/domestic-tours',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomItineraryRoute = CustomItineraryRouteImport.update({
  id: '/custom-itinerary',
  path: '/custom-itinerary',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsRoute = BlogsRouteImport.update({
  id: '/blogs',
  path: '/blogs',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToursTourIdRoute = ToursTourIdRouteImport.update({
  id: '/tours/$tourId',
  path: '/tours/$tourId',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSlugRoute = BlogsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/custom-itinerary': typeof CustomItineraryRoute
  '/destinations': typeof DestinationsRoute
  '/domestic-tours': typeof DomesticToursRoute
  '/egypt': typeof EgyptRoute
  '/faq': typeof FaqRoute
  '/international-tours': typeof InternationalToursRoute
  '/travel-insurance': typeof TravelInsuranceRoute
  '/visa': typeof VisaRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/tours/$tourId': typeof ToursTourIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/custom-itinerary': typeof CustomItineraryRoute
  '/destinations': typeof DestinationsRoute
  '/domestic-tours': typeof DomesticToursRoute
  '/egypt': typeof EgyptRoute
  '/faq': typeof FaqRoute
  '/international-tours': typeof InternationalToursRoute
  '/travel-insurance': typeof TravelInsuranceRoute
  '/visa': typeof VisaRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/tours/$tourId': typeof ToursTourIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blogs': typeof BlogsRouteWithChildren
  '/contact': typeof ContactRoute
  '/custom-itinerary': typeof CustomItineraryRoute
  '/destinations': typeof DestinationsRoute
  '/domestic-tours': typeof DomesticToursRoute
  '/egypt': typeof EgyptRoute
  '/faq': typeof FaqRoute
  '/international-tours': typeof InternationalToursRoute
  '/travel-insurance': typeof TravelInsuranceRoute
  '/visa': typeof VisaRoute
  '/blogs/$slug': typeof BlogsSlugRoute
  '/tours/$tourId': typeof ToursTourIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/custom-itinerary'
    | '/destinations'
    | '/domestic-tours'
    | '/egypt'
    | '/faq'
    | '/international-tours'
    | '/travel-insurance'
    | '/visa'
    | '/blogs/$slug'
    | '/tours/$tourId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/custom-itinerary'
    | '/destinations'
    | '/domestic-tours'
    | '/egypt'
    | '/faq'
    | '/international-tours'
    | '/travel-insurance'
    | '/visa'
    | '/blogs/$slug'
    | '/tours/$tourId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blogs'
    | '/contact'
    | '/custom-itinerary'
    | '/destinations'
    | '/domestic-tours'
    | '/egypt'
    | '/faq'
    | '/international-tours'
    | '/travel-insurance'
    | '/visa'
    | '/blogs/$slug'
    | '/tours/$tourId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogsRoute: typeof BlogsRouteWithChildren
  ContactRoute: typeof ContactRoute
  CustomItineraryRoute: typeof CustomItineraryRoute
  DestinationsRoute: typeof DestinationsRoute
  DomesticToursRoute: typeof DomesticToursRoute
  EgyptRoute: typeof EgyptRoute
  FaqRoute: typeof FaqRoute
  InternationalToursRoute: typeof InternationalToursRoute
  TravelInsuranceRoute: typeof TravelInsuranceRoute
  VisaRoute: typeof VisaRoute
  ToursTourIdRoute: typeof ToursTourIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel-insurance': {
      id: '/travel-insurance'
      path: '/travel-insurance'
      fullPath: '/travel-insurance'
      preLoaderRoute: typeof TravelInsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international-tours': {
      id: '/international-tours'
      path: '/international-tours'
      fullPath: '/international-tours'
      preLoaderRoute: typeof InternationalToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/egypt': {
      id: '/egypt'
      path: '/egypt'
      fullPath: '/egypt'
      preLoaderRoute: typeof EgyptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/domestic-tours': {
      id: '/domestic-tours'
      path: '/domestic-tours'
      fullPath: '/domestic-tours'
      preLoaderRoute: typeof DomesticToursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-itinerary': {
      id: '/custom-itinerary'
      path: '/custom-itinerary'
      fullPath: '/custom-itinerary'
      preLoaderRoute: typeof CustomItineraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs': {
      id: '/blogs'
      path: '/blogs'
      fullPath: '/blogs'
      preLoaderRoute: typeof BlogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tours/$tourId': {
      id: '/tours/$tourId'
      path: '/tours/$tourId'
      fullPath: '/tours/$tourId'
      preLoaderRoute: typeof ToursTourIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$slug': {
      id: '/blogs/$slug'
      path: '/$slug'
      fullPath: '/blogs/$slug'
      preLoaderRoute: typeof BlogsSlugRouteImport
      parentRoute: typeof BlogsRoute
    }
  }
}

interface BlogsRouteChildren {
  BlogsSlugRoute: typeof BlogsSlugRoute
}

const BlogsRouteChildren: BlogsRouteChildren = {
  BlogsSlugRoute: BlogsSlugRoute,
}

const BlogsRouteWithChildren = BlogsRoute._addFileChildren(BlogsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogsRoute: BlogsRouteWithChildren,
  ContactRoute: ContactRoute,
  CustomItineraryRoute: CustomItineraryRoute,
  DestinationsRoute: DestinationsRoute,
  DomesticToursRoute: DomesticToursRoute,
  EgyptRoute: EgyptRoute,
  FaqRoute: FaqRoute,
  InternationalToursRoute: InternationalToursRoute,
  TravelInsuranceRoute: TravelInsuranceRoute,
  VisaRoute: VisaRoute,
  ToursTourIdRoute: ToursTourIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
